### ISSUE TITLE
Include boards and commissions with no liaison set in liaison list

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#101]
When viewing the list of liaisons, it will be useful to include those boards and commissions that do not have a liaison assigned in the system. This will make it easier to track down those boards that still need this information:

[https://bloomington.in.gov/onboard/liaisons](url)

**Comment by rbdietz** [comment]
Might just organize the liaison list by boards, then lists however many liaisons there are below the board title.
