### ISSUE TITLE
Trying to add new user with role Reviewer yields error

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#103]
This may not have anything to do with the chosen role (Reviewer), but when I try to add user wanzers I get the following error:

Sorry

Statement could not be executed (23000 - 1062 - Duplicate entry 'wanzers@bloomington.in.gov' for key 'email')

**Comment by inghamn** [comment]
Those people are already in the system.  The error message can be worked on.  It's expected to look up the person, and add a user account for them, rather than creating another person record.

**Comment by charlesbrandt** [comment]
I am getting this when I try to "Create Account" not add a new person. The page that I get this error on is:
https://bloomington.in.gov/onboard/users
