### ISSUE TITLE
Field to track legal liaison for boards and commissions

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#105]
We could add this as part of the existing liaison management system for onBoard, but there should be a distinction that the specified liaison is specific to legal. We will want to be able to list all legal liaisons separately from all other liaisons.

**Comment by charlesbrandt** [comment]
These should be referred to as "Attorney Staff"

**Comment by inghamn** [comment]
This opens up questions about what to do in the places we're currently displaying liaison information.  Do we have ideas on how we want this to work?

https://bloomington.in.gov/onboard/liaisons
https://bloomington.in.gov/onboard/committees/info?committee_id=3
https://bloomington.in.gov/onboard/people/view?person_id=517

**Comment by inghamn** [comment]
For the liaisons list, we're going to create a tab for seach separate liaison type. (departmental, legal)

For the committee and person views, we'll just add a field to display the type of liaison.
