### ISSUE TITLE
Page Titles

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/OnBoard#109]
Every page should have an appropriate html page title for the browser/tabs to display

**Comment by charlesbrandt** [comment]
Agreed. Thought we got this with #89, but that must have been specific to committee pages. Do you remember which page you noticed without a page title?

**Comment by rbdietz** [comment]
major tabs: people, seats, liasons, apply
all admin pulldown menu pages

 It should be a part of our process to insure that all URLs are meaningful.
My preference would be for all pages to be of the form:
onBoard: Board of Public Safety
onBoard: Laisons
onBoard: Rick Dietz
Or something similar


On Thu, Mar 10, 2016 at 11:32 AM, Charles Brandt <notifications@github.com>
wrote:

> Agreed. Thought we got this with #89
> <https://github.com/City-of-Bloomington/OnBoard/issues/89>, but that must
> have been specific to committee pages. Do you remember which page you
> noticed without a page title?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/City-of-Bloomington/OnBoard/issues/109#issuecomment-194939406>
> .
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~
Rick Dietz, Director
Information & Technology Services Dept.
City of Bloomington, Indiana
812.349.3485 (office) 812.340.7958 (cell)
dietzr@bloomington.in.gov

**Comment by hiesterd** [comment]
What would you think of putting the name of the application or service last? For example:

Board of Public Safety – onBoard: City of Bloomington, Indiana
Laisons – onBoard: City of Bloomington, Indiana
Rick Dietz – onBoard: City of Bloomington, Indiana

This way, if someone is working with onBoard from multiple tabs, they have a better chance of seeing which page is open on each tab.

As a secondary suggestion, what about the title effectively being breadcrumbs, displayed in reverse order, to give a more complete sense of context? For example:

Laisons – Board of Public Safety – onBoard: City of Bloomington, Indiana

**Comment by rbdietz** [comment]
I'm fine with that too.

On Thu, Mar 10, 2016 at 3:32 PM, Dan Hiester <notifications@github.com>
wrote:

> What would you think of putting the name of the application or service
> last? For example:
>
> Board of Public Safety – onBoard: City of Bloomington, Indiana
> Laisons – onBoard: City of Bloomington, Indiana
> Rick Dietz – onBoard: City of Bloomington, Indiana
>
> This way, if someone is working with onBoard from multiple tabs, they have
> a better chance of seeing which page is open on each tab.
>
> As a secondary suggestion, what about the title effectively being
> breadcrumbs, displayed in reverse order, to give a more complete sense of
> context? For example:
>
> Laisons – Board of Public Safety – onBoard: City of Bloomington, Indiana
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/City-of-Bloomington/OnBoard/issues/109#issuecomment-195034971>
> .
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~
Rick Dietz, Director
Information & Technology Services Dept.
City of Bloomington, Indiana
812.349.3485 (office) 812.340.7958 (cell)
dietzr@bloomington.in.gov
