### ISSUE TITLE
Staff cannot add people to the system

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/OnBoard#120]
We do want Staff to be able to add people and liaisons to the system.

This was removed when we created the Reviewer role.

**Comment by rbdietz** [comment]
Diane needs to be able to Add people and Admins too. R

On Tue, Mar 22, 2016 at 11:38 AM, Cliff Ingham <notifications@github.com>
wrote:

> Closed #120 <https://github.com/City-of-Bloomington/OnBoard/issues/120>
> via 0fe61bd
> <https://github.com/City-of-Bloomington/OnBoard/commit/0fe61bd0fdc404182affc9b66de79ea6f03cc768>
> .
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/City-of-Bloomington/OnBoard/issues/120#event-598889113>
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~
Rick Dietz, Director
Information & Technology Services Dept.
City of Bloomington, Indiana
812.349.3485 (office) 812.340.7958 (cell)
dietzr@bloomington.in.gov
