### ISSUE TITLE
Navigation buttons do not show which is current

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/OnBoard#121]
We are not showing which button you clicked when displaying a set of navigation buttons. 

We are currently doing this on 
/committees/members
/liaisons
/seats
/seats/vacancies

Do we want to do different one of the buttons as "current" or "active" to show the user which screen they're looking at?  Clicking the active one will just refresh the page.

**Comment by charlesbrandt** [comment]
This has been mentioned in passing, and I think it is worth looking in to. It seems like many sites use the strategy where the currently selected page is highlighted with a different color, bolded, and underlined. For example:
<img width="826" alt="screen shot 2016-03-22 at 3 35 46 pm" src="https://cloud.githubusercontent.com/assets/2225624/13965253/d693e710-f043-11e5-9333-f4387a0a791c.png">

Dan, any thoughts on this?

**Comment by hiesterd** [comment]
I'm confident that would improve the user experience. I think it makes most sense to implement this in Factory Number One, so that it would be available to all of our applications that use that project, moving forward. It would be a pretty minor feature to add.

Should I add an issue to that project and execute the addition?

**Comment by charlesbrandt** [comment]
Sure, you can add an issue there. Just make sure to apply the pattern to onBoard and close this issue as well.

**Comment by hiesterd** [comment]
I've updated the stylesheet with the CSS necessary to implement. I'm not sure how to best, in our framework, change an HTML class attribute based on the active route. @inghamn, is this something you'd like to add with me? Is there an example in another application you would like me to emulate? Or would you prefer to take over from here?

**Comment by charlesbrandt** [comment]
Thanks for pointing out the duplicate...

Lets add a .selected class to the corresponding secondary nav button (Information, Current Members, etc) and set .selected to have a background color: #FCECC9

**Comment by inghamn** [comment]
Fixed in 4591c0effe246da3ee629b3c7505aa7157c7034f
