### ISSUE TITLE
Past committees should show up below current Committees on list

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#125]
[https://bloomington.in.gov/onboard/committees](url)

**Comment by inghamn** [comment]
When listing the past committees, for each committee, where should we point the link?  Should we link to:

* committees/info
* committees/members
* committees/pastMembers

**Comment by charlesbrandt** [comment]
I think to be consistent with the behavior of current committees, it would make the most sense to link to pastMemebers
