### ISSUE TITLE
On Members page, show Past Members button if past members exist

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#126]
Rather than include these below below current members, create a new route for past members so that existing views for current members (e.g. csv) will continue to make sense.

**Comment by inghamn** [comment]
What should the past members screen look like?  

The current members screen is by seat.  That works very well when there's only one member per seat.  When listing past members you're going to have lots of past members per seat.

**Comment by charlesbrandt** [comment]
Can we mimic / reuse the same patterns we use for current members? Even on previous committees it makes sense to group by seats and then see the history of that given seat. Ideally this would avoid implementing a new interface to display this information.

**Comment by hiesterd** [comment]
What is the difference between previous members, as we're discussing them here, and previous terms, as implemented on the Seat Detail View?

![screen shot 2016-03-29 at 9 56 48 am](https://cloud.githubusercontent.com/assets/10146145/14110492/ab74d214-f594-11e5-95b9-d5f3446d571b.png)

**Comment by inghamn** [comment]
I'm assuming that Committee->previous members is supposed to be the same as
Committee->current members.  Different information is being displayed.

Look at the table columns in current members.  I'm guessing we need to
display seat names, seat codes, and appointment information for each
previous member.  (In addition to, of course, their name and term dates).


Cliff Ingham
Web Developer
City of Bloomington, Indiana

https://github.com/City-of-Bloomington
https://openhub.net/accounts/inghamn
