### ISSUE TITLE
Liaison adding is not working

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/OnBoard#132]
```
Call to undefined method Application\Models\Committee::saveLiaison()

Array
(
    [timestamp] => DateTime Object
        (
            [date] => 2016-04-09 17:38:42.000000
            [timezone_type] => 3
            [timezone] => America/Indiana/Indianapolis
        )

    [priority] => 3
    [priorityName] => ERR
    [message] => Call to undefined method Application\Models\Committee::saveLiaison()
    [extra] => Array
        (
            [file] => /srv/sites/onboard/Controllers/LiaisonsController.php
            [line] => 41
        )

)
```

**Comment by charlesbrandt** [comment]
Not sure if this is a separate issue, but there doesn't seem to be a way to choose what type of Liaison is being added in the Add Liaison page.

**Comment by inghamn** [comment]
Turns out the Liaison type stuff was only halfway built, and yet, I still closed the issue.  Stupid me.

**Comment by charlesbrandt** [comment]
What determines / configures the first column in the liaison section? If it is just the department associated with the Board and Commission, then it is redundant information that should be omitted. 

If it is assigned on a liaison by liaison basis, then there should be a way to choose it.

**Comment by inghamn** [comment]
It is the department for the committee.  I can edit the HTML to just not display department information
