### ISSUE TITLE
Resign action not showing up on all current members

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/OnBoard#136]
For instance, the Utilities Service Board, Tom Swaford

**Comment by inghamn** [comment]
Turns out we did not account for resigning a person who's already been replaced.

We still want to display the resign action, even when there's someone already signed up for the next term.  We need to be able to show who will fill out the remainder of the current term.

**Comment by charlesbrandt** [comment]
I thought that if someone was appointed for a subsequent term, then that action would set an appropriate end date for the current person being replaced. 

If somehow the current person's term does not have an end date set, then I agree we will still want to show the resign action to fix this.
