### ISSUE TITLE
Mailing list for Liaisons

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/OnBoard#142]
We should have a bit on the liaisons list page that allows admins to copy the list of liaisons to be able to email them or triggers a mailto: action

**Comment by charlesbrandt** [comment]
Is the main purpose for this function to send a request to review the current content and configuration for the corresponding board or commission? In that case, it may be best to make that an "Admin" function where the onBoard system would generate and send the message to each liaison. The benefit with this approach is that we could include a direct link to the corresponding board or commission(s) that the liaison represents in the message. 

But maybe the list copy is a faster solution.

**Comment by rbdietz** [comment]
The main purpose is to be able to send arbitrary messages to all liaisons.
I just want the list because I want folks to be able to reply to me.  I'm
not wanting to build in a messaging system at this point just get a
copy&pasteable comma separated list of email addresses.

**Comment by rbdietz** [comment]
This does not produce a usable email list.  Please remove the duplicates.

**Comment by inghamn** [comment]
Moved the latest fix to a new issue: #147
