### ISSUE TITLE
Create an applicant viewing role

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/OnBoard#149]
We have a user that needs to be able to see applications for boards, and their applications.  However, we do not want this role to be able to edit anything.

I think this is to mean, this role should be able to view applications that have been selected for positions by the "Reviewer" role.

**Comment by inghamn** [comment]
The Reviewer role does not actually persist the reports that they generate.  That feature was intended as a way for the Reviewer to generate a display which could be printed out on paper.  Then, the paper copies would be delivered to the people who screened applicants.

We'll need to implement a way to persist the report that the Reviewer role generates.

**Comment by rbdietz** [comment]
I'm confused by this.  The only difference with a Reviewer should be that
the person cannot delete or archive applications/applicants.   They should
not be depending on "reviewers" making a report.

**Comment by inghamn** [comment]
I'll rename it to "Applicants view-only".  It's more explicit.  These are
just labels for the role.  The permissions are what really counts.


Cliff Ingham
Web Developer
City of Bloomington, Indiana

https://github.com/City-of-Bloomington
https://openhub.net/accounts/inghamn

**Comment by inghamn** [comment]
Okay, I've updated the role name to "Applicants-view-only"


Cliff Ingham
Web Developer
City of Bloomington, Indiana

https://github.com/City-of-Bloomington
https://openhub.net/accounts/inghamn

**Comment by rbdietz** [comment]
Please add the council members to have this view-only permission

**Comment by inghamn** [comment]
Okay, I've created user accounts for all members of the city council


Cliff Ingham
Web Developer
City of Bloomington, Indiana

https://github.com/City-of-Bloomington
https://openhub.net/accounts/inghamn
