### ISSUE TITLE
Apply forms need captcha service to help minimize spam

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#150]
Boards are starting to receive junk / spam applications for seats. Placing a captcha on the application form should help mitigate some of this. 

As an example, see archived applications here:
https://bloomington.in.gov/onboard/committees/applications?committee_id=16

**Comment by inghamn** [comment]
We should also build a way to delete applicants and applications.

In cases like these, just moving them to "archived" doesn't help so much. You still have to wade through all the spam to see real people.
