### ISSUE TITLE
Clean up "Committee Info" redundant fields

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#152]
As the information that we collect about Committees has evolved, we've ended up with some fields that are redundant. Committees have:
- Email
- Phone
- Contact Information
- Liaisons

In some cases there is a lot of overlap between those fields. May want to consider if there is a way to consolidate those.

**Comment by inghamn** [comment]
I'm working on removing the contactInfo field, in favor of using the individual fields (email, phone, address, etc.)
