### ISSUE TITLE
Allow choosing date when editing Meeting Files

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/OnBoard#166]
We want the user to be able to choose a date on the "edit meeting file" screen.  However, we only want them to be able to choose from events that are in the Google Calendar for the committee.

**Comment by rbdietz** [comment]
Is this correct for "other" files?  Probably, but I'm not certain.  R





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by inghamn** [comment]
This is implemented in the latest release
