### ISSUE TITLE
Allow for more granular term dates

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#169]
A few boards or commissions specify that terms end on a certain day of a certain week in a year, rather than a specific date. The current system does not accommodate this style of term definition; currently a seat term is defined by a number of years (1 year, 2 years, 3 years, etc). 

Specifying a term to end on a certain day of the week is potentially possible, but will add complexity to the interface and underlying code. If this is a desired feature, we will need to schedule time for development. 

In the meantime we are exploring adjusting term dates manually for those boards that require them.

**Comment by rbdietz** [comment]
Please quantify.  Which boards and how many seats?  Seems like this would
be a low priority to fix unless it's a real problem.  R





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by charlesbrandt** [comment]
I agree that this is low priority. The committees that were affected by this include: Board of Zoning Appeals, Plan Commission, and Plat Commission. It may be worth investigating if these committees require the exception.

**Comment by charlesbrandt** [comment]
So far the fix has been to manually adjust these terms when the issue comes up. Automating this would be very involved.
