### ISSUE TITLE
Add Liaison Role

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/OnBoard#171]
We want to add a role for Liaisons.  We'll start out with the Liaison role just having permission to edit Meeting Files (Agendas, Minutes, Packets).    We can chance the role permissions easily in the future.

Or....more precisely....
We need a role to assign to users who are going to manage minutes and agendas.  It seems like the majority of users we'll be adding for this are Liaisons.  It seems to make sense to start with calling the role "Liaisons", and we can change it, easily, later.

**Comment by rbdietz** [comment]
There are people who are not liaisons that will be uploading minutes and
agendas.  How does this work?





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by inghamn** [comment]
The name of the role is just an arbitrary label.  If calling it, "Liaisons" is too confusing, we can rename it.  Would calling it "meetingFileUploaders" be better?

At least until we decide we need some other permission added to it.  Then we'd probably want to rename it to match the new permissions we've assigned to it.  Really, though it's just a name.  I've been attempting to use words we already use to name the roles, but the role names can be anything.

**Comment by rbdietz** [comment]
fileUploaders seems fine to me.  Just don't want to confuse with existing
regular and legal liaisons.  R






Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by inghamn** [comment]
meetingFileUploaders would be more accurate, as there are also Application Files, which this role cannot upload.

**Comment by rbdietz** [comment]
Sounds fine, thanks. R





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov
