### ISSUE TITLE
Remove description field for Committees

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/OnBoard#184]
The about information for each board is being maintained in two places now.  The website has a page for each board, which we link to using the committee's website field.

We should remove the "about" field from committees, and rely on the city website for this information.

See #182 
See #183

**Comment by rbdietz** [comment]
We should maintain this information in onBoard.  This is information that
can de used outside of the website in data feeds and other services.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by charlesbrandt** [comment]
Managing this in onboard adds complexity and confusion for those who are maintaining the information on the website. If we include a link in onBoard to the source on the website it would still be possible to pull the information from a corresponding field in drupal for any other syndication.

**Comment by rbdietz** [comment]
How much of a problem is this really?  Is this different from the
'description' field?





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by charlesbrandt** [comment]
It's not a big problem... we were just trying to clean up information that is duplicated in more than one system to another to avoid confusion about what is the authoritative source of the information. 

We can keep the board's 'description' field in onboard, but we do not want to use it as the source of the description for the website page. That would require integration and add confusion to the system.

**Comment by inghamn** [comment]
After further review, the field in question is the committee "description" in OnBoard.  On our drupal website, it equates to the content on the page for the board.

**Comment by rbdietz** [comment]
Descriptions needs to stay in onBoard.  Not all potential users of onBoard as open source will be integrating it as we are into Drupal.

**Comment by inghamn** [comment]
Should we modify Drupal to display OnBoard's committee description, instead of employees hand-typing the content into a page in Drupal?

**Comment by charlesbrandt** [comment]
As I've stated earlier in this thread, I would prefer not to use OnBoard as the source of this description in Drupal. I think we tried this in the past and it lead to confusion about where to go to edit the information. Given the desire to keep the description in OnBoard as well, I think it's acceptable to keep the (potentially redundant) description in both systems. Feel free to re-open if others do not agree.
