### ISSUE TITLE
Allow for meetings to be queried by date range

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/OnBoard#187]
Right now, the only parameter the meetings query takes is the year.  This assumes we're only ever asking for a year at a time, and always for a full year.

We'd like to have OnBoard provide the meeting events data for our Drupal board pages.  (They currently talk to Google Calendar directly.)  The query needs to support start and end dates as parameters.  That way we can request the meeting dates for a customizable range.

**Comment by rbdietz** [comment]
Also individual date





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov
