### ISSUE TITLE
Notify staff liaisons when new applications arrive

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#196]
Eric Sader asked about liaisons receiving notifications when a new application arrives for the corresponding board or commission. We should explore what is necessary to send this notification.

**Comment by rbdietz** [comment]
Perhaps a weekly report of activities in liaison commissions would be
better...

Liaison Report for Liaison John Smith
Week of 8/1/17 - 8/8/17

Committee 1
Vacancies:2 (Mayor appointment, Council Appointment)
Current Applications: 3 John doe, jane doe, jeff doe
New applications this week: 1 Alan Smithy
Documents added: minutes 8/1/17, agenda 8/15/2017

Committee 2
Vacancies:2 (Mayor appointment, Council Appointment)
Current Applications: 3 John doe, jane doe, jeff doe
New applications this week: 1 Alan Smithy
Documents added: minutes 8/1/17, agenda 8/15/2017







Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by inghamn** [comment]
Are liaisons the people who review the applicants?  We have a "Reviewer" role, different from Liaisons, who we've delegated that permission.

**Comment by rbdietz** [comment]
Probably makes sense for everyone to get a summary.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by rbdietz** [comment]
Liaisons are usually not the people that actual make appointments.

**Comment by inghamn** [comment]
Should we not send alerts to Liaisons at all, then?

**Comment by charlesbrandt** [comment]
No, but if they facilitate access to the applications for other board members then it is still useful for them to receive notice that there are new applications.

**Comment by charlesbrandt** [comment]
Cliff's reply came in at the same time -- to clarify, I think we should be sending alerts.
