### ISSUE TITLE
Come up with a new name for this project

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/OnBoard#2]
We need to discuss a more fitting name for this project

**Comment by charlesbrandt** [comment]
The name "OnBoard" has been in use internally for a while now. The repository has been updated to reflect this name.

**Comment by rbdietz** [comment]
Please camel case this project for consistency with uReport and inRoads.

**Comment by hiesterd** [comment]
We could rename the project to uBoard to be *even more* consistent.

**Comment by charlesbrandt** [comment]
Cliff has already done some refactoring of other projects that integrate onBoard... case shouldn't have an impact on that. It doesn't look like github allows changing the case in the settings. We may be stuck with OnBoard here, but can use onBoard everywhere else.

**Comment by rbdietz** [comment]
Sounds fine. OnBoard / onBoard it's all the same. R

On Wed, Jan 20, 2016 at 8:59 AM, Charles Brandt <notifications@github.com>
wrote:

> Cliff has already done some refactoring of other projects that integrate
> onBoard... case shouldn't have an impact on that. It doesn't look like
> github allows changing the case in the settings. We may be stuck with
> OnBoard here, but can use onBoard everywhere else.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/City-of-Bloomington/OnBoard/issues/2#issuecomment-173212008>
> .
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~
Rick Dietz, Director
Information & Technology Services Dept.
City of Bloomington, Indiana
812.349.3485 (office) 812.340.7958 (cell)
dietzr@bloomington.in.gov
