### ISSUE TITLE
Created page for Committee #53. Caused an error.

### ISSUE THREAD

**Issue by quarterback** [City-of-Bloomington/OnBoard#203]
![screen shot 2017-08-22 at 3 50 32 pm](https://user-images.githubusercontent.com/4461062/29584284-44fd48f4-8751-11e7-9df2-5fa60f6b47be.png)

**Comment by inghamn** [comment]
This will need to be fixed in the drupal module.

https://github.com/City-of-Bloomington/drupal-module-onboard/issues/9

**Comment by charlesbrandt** [comment]
Please use https://github.com/City-of-Bloomington/drupal-module-onboard/issues/9 for updates
