### ISSUE TITLE
Dropdowns

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/OnBoard#212]
Dropdown menus on Membership pages are all open is MacOSX on Chrome
![screen shot 2017-10-31 at 3 09 30 pm](https://user-images.githubusercontent.com/1135994/32244037-a91a68f2-be4d-11e7-8108-1b9972297c54.png)

**Comment by inghamn** [comment]
Problem was resolved by clearing the cache.  One day we should maybe compile our JS and use a build number in the filename.  That way filenames for new versions would always be different, and thus, not cached.
