### ISSUE TITLE
Need a way to remove reports

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#214]
Currently, after a report has been uploaded there is no way to delete it. If the wrong file is uploaded then there isn't any way to fix the mistake. Here is an example of a file that has been requested to be removed:

https://bloomington.in.gov/onboard/reports?committee_id=38

**Comment by inghamn** [comment]
Fixed in 893cce55c431860d502633c48a01711762159f1a
