### ISSUE TITLE
Only send application alerts to staff liaison

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#216]
Now that #196 is in place and sending alerts, we should limit those to only send to staff liaisons. It looks like legal liaisons are also getting alerts, but I don't think they play a role in deciding on applicants.

**Comment by rbdietz** [comment]
Correct.  Legal liaisons have little to no role with appointments.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by rbdietz** [comment]
I'm not sure how universal the desire would be to get applicants notifications.  It might be worthwhile to poll the liaisons and see before putting this into action.  R

**Comment by charlesbrandt** [comment]
I also wanted to add a reminder that the language file is not being applied in the message that is generated, so liaisons are receiving messages that look like: 

Subject: board_application_subject

board_application_message

https://bloomington.in.gov/onboard/committees/applications?committee_id=8

**Comment by inghamn** [comment]
I have not been able to replicate this problem.  Every test I've run on staging and production results in a correctly formatted email.
