### ISSUE TITLE
Enable/Disable applications on a per-committee basis

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/OnBoard#217]
We currently render a link to apply for a position on all boards and committees with vacancies.  This does not take into account that only some positions are appointed.  Elected positions are not something you apply for.

**Comment by rbdietz** [comment]
It might make more sense to apply this on a per position basis.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by inghamn** [comment]
Yeah, this will need to be done on a per-seat basis.  We'll also need to update the drupal module to show board member vacancies differently, depending on the whether they can apply for the seat or not.

**Comment by inghamn** [comment]
This issue is blocking: https://github.com/City-of-Bloomington/drupal-module-onboard/issues/27

**Comment by inghamn** [comment]
This is blocking: https://github.com/City-of-Bloomington/drupal-theme-cob/issues/144

**Comment by inghamn** [comment]
#463
