### ISSUE TITLE
Include member addresses in seats CSV download

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/OnBoard#287]
We need to compile the mailing addresses for all board and commission members.  The seats CSV download seems like the best place to put that.

**Comment by rbdietz** [comment]
Should we include personal addresses in this list?  It's posted to the data
portal. R



Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0076 Cell
bloomington.in.gov

**Comment by inghamn** [comment]
The personal information is only included the CSV if you are logged in and have permission to view personal information.  The CSV data that's uploaded to the data portal is from a non-authenticated request, so it doesn't include contact information.

**Comment by rbdietz** [comment]
Great, thanks. R




Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0076 Cell
bloomington.in.gov
