### ISSUE TITLE
url demo or screenshots

### ISSUE THREAD

**Issue by johnfelipe** [City-of-Bloomington/OnBoard#29]

**Comment by inghamn** [comment]
This is a backend application, that provides data via web services to the rest of our web applications.  I don't have a demo URL installed.  The best I can do right now is a few screenshots.
![board](https://cloud.githubusercontent.com/assets/630282/9578587/4d3129e0-4fb9-11e5-957b-8c070250263f.png)
![committees](https://cloud.githubusercontent.com/assets/630282/9578589/4d367d0a-4fb9-11e5-9a85-3640be6eea7a.png)
![seats](https://cloud.githubusercontent.com/assets/630282/9578588/4d3308f0-4fb9-11e5-9bf4-c55af26f29dd.png)

**Comment by charlesbrandt** [comment]
We have decided to make this web application a public resource now that it handles our application process. The public URL of our instance of the service is:

https://bloomington.in.gov/onboard

This does not have any of the administration features enabled for the public.
