### ISSUE TITLE
Generate CSV output of current state

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#39]
It should be possible to export a CSV file containing:

 - current vacancies and
 - full commission memberships

The output for the full commission memberships should include:
Board Name,Seat Name / Type,Appointed By,Person,Current Term Dates

This functionality should be available to everyone. 
This functionality may satisfy issue #5

**Comment by rbdietz** [comment]
We should have two feeds.  One for the complete roster of seats (inc
vacancies) and one for just vacancies.

On Wed, Jan 20, 2016 at 12:12 PM, Cliff Ingham <notifications@github.com>
wrote:

> Closed #39 <https://github.com/City-of-Bloomington/OnBoard/issues/39>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/City-of-Bloomington/OnBoard/issues/39#event-520635011>
> .
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~
Rick Dietz, Director
Information & Technology Services Dept.
City of Bloomington, Indiana
812.349.3485 (office) 812.340.7958 (cell)
dietzr@bloomington.in.gov
