### ISSUE TITLE
People

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/OnBoard#4]
People table needs...

a field for personal URL (homepage, blog, facebook or twitter)

Also for race we should use these census categories and descriptions.  Users may select more than one category.  These are not mutually exclusive.

White – A person having origins in any of the original peoples of Europe, the Middle East, or North Africa.

Black or African American – A person having origins in any of the Black racial groups of Africa.

American Indian or Alaska Native – A person having origins in any of the original peoples of North and South America (including Central America) and who maintains tribal affiliation or community attachment.

Asian – A person having origins in any of the original peoples of the Far East, Southeast Asia, or the Indian subcontinent including, for example, Cambodia, China, India, Japan, Korea, Malaysia, Pakistan, the Philippine Islands, Thailand, and Vietnam.

Native Hawaiian or Other Pacific Islander – A person having origins in any of the original peoples of Hawaii, Guam, Samoa, or other Pacific Islands.

Hispanic or Latino Origin -  People who classify themselves as “Mexican, Mexican Am., Chicano” or ”Puerto Rican” or “Cuban” – as well as “another Hispanic, Latino, or Spanish origin."  People who identify their origin as Hispanic, Latino, or Spanish may be of any race.

**Comment by inghamn** [comment]
#392
