### ISSUE TITLE
Committee calendars

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/OnBoard#54]
We want to reference the Google Calendar ID for each committee.

Not sure if we want to display the actual calendar, somehow, in OnBoard, though.

**Comment by charlesbrandt** [comment]
We don't need to display the calendar in onBoard right now. Just a field to track the google calendar ID at the committee level will be sufficient.

**Comment by charlesbrandt** [comment]
#81 was a duplicate for this one. We've decided to keep the calendar id separate from onBoard.
