### ISSUE TITLE
Specify range of termEndsSoon at the Committee level

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#55]
At the board or committee, it should be possible to configure how far ahead an end date triggers the termEndsSoon style. Default should be set to 1 month

**Comment by rbdietz** [comment]
I don't think 1 month is sufficient for the default.  Let's go with 2.

On Tue, Jan 26, 2016 at 2:20 PM, Cliff Ingham <notifications@github.com>
wrote:

> Closed #55 <https://github.com/City-of-Bloomington/OnBoard/issues/55> via
> 751e031
> <https://github.com/City-of-Bloomington/OnBoard/commit/751e0315fe51808711e5ee3a19d574816626956c>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/City-of-Bloomington/OnBoard/issues/55#event-526970317>
> .
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~
Rick Dietz, Director
Information & Technology Services Dept.
City of Bloomington, Indiana
812.349.3485 (office) 812.340.7958 (cell)
dietzr@bloomington.in.gov
