### ISSUE TITLE
Unable to add multiple memberships to a single term

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#59]
For seat:
http://rogue.bloomington.in.gov/boards-staging/seats/view?seat_id=108

I was trying to add Kelly Smith with a membership of: 1/1/2013 - 12/22/2013 to avoid overlap with John West's membership from 12/23/2013 - 12/31/2013. 

However, when I try to create this appointment, I get:

    Sorry
    members/overlappingTerms

**Comment by inghamn** [comment]
Was not able to reproduce the problem.  I'll leave this around for us if we have the problem again

**Comment by charlesbrandt** [comment]
I was not able to reproduce it either. Will re-open if it happens again.
