### ISSUE TITLE
Admin appoint member to whole term checkbox

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#60]
When using the seat admin section to appoint a member to a term, it would be helpful to have a check box on the Appoint screen that says "Appoint for whole term" that automatically uses the term's start and end dates when creating the membership.

example admin page:
http://rogue.bloomington.in.gov/boards-staging/members/update?term_id=218

**Comment by inghamn** [comment]
I wrote code to auto-populate some valid dates using my best guess.

* It will use the term dates, if it's a past term.
* For current or future terms, it will only set the startDate to today.
* If there are other members in the term, no dates will be populated.
