### ISSUE TITLE
Combine 'member' and 'vacancies' tabs into 'positions'

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#63]
The new tab, "Positions" will be a way to look at all available Positions (aka Seats). The default should be to see all seats, including vacancies. There should be the option to filter to see only Vacant seats (this includes seats in a carryover status, technically vacant). 

Each of the different filtered views should also have the ability to export that configuration as a CSV.

**Comment by inghamn** [comment]
Do we want to change the word "Seats" to "Positions" everywhere, so we are not using different words for the same thing?

**Comment by charlesbrandt** [comment]
There is some ambiguity there since we are using both terms for the same thing. I don't have a strong preference either way, but I agree that we should be consistent. Rick, do you prefer "Positions" over "Seats"? We've been using "Seats" pretty consistently until yesterday.

**Comment by rbdietz** [comment]
"Seats" is fine.

On Tue, Jan 26, 2016 at 11:35 AM, Charles Brandt <notifications@github.com>
wrote:

> There is some ambiguity there since we are using both terms for the same
> thing. I don't have a strong preference either way, but I agree that we
> should be consistent. Rick, do you prefer "Positions" over "Seats"? We've
> been using "Seats" pretty consistently until yesterday.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/City-of-Bloomington/OnBoard/issues/63#issuecomment-175104952>
> .
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~
Rick Dietz, Director
Information & Technology Services Dept.
City of Bloomington, Indiana
812.349.3485 (office) 812.340.7958 (cell)
dietzr@bloomington.in.gov
