### ISSUE TITLE
Different iconography for different states of a given seat

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#65]
We currently have a red "!" icon for seats in a carry over state. We also need different icons to represent a vacant seat and a seat that is "Soon to expire"

**Comment by inghamn** [comment]
I'm pretty sure this is implemented already.

All carryovers are vacant.  Vacant and Carryover use the same icon (only once, not twice).
Soon to expire gets a yellow color and different icon

**Comment by hiesterd** [comment]
Correct. An icon was already there for appointments near expiration. We decided yesterday to use the same icon for both a vacancy and carryover, so that made the work to finish this issue trivial.
