### ISSUE TITLE
Seat list on edit seat should be below edit form

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#73]
A recent change added the seat list to the page with the form for editing a seat:
http://rogue.bloomington.in.gov/boards-staging/seats/update?seat_id=113

Now accessing the form requires scrolling. It is OK to have the seat list on that page, but it should be below the edit form.

**Comment by charlesbrandt** [comment]
The same should go for the "Add Appointee" form... other terms for the current seat should be below the form for editing. These can get long and it becomes difficult to access the form for editing. 
http://rogue.bloomington.in.gov/boards-staging/members/update?term_id=252

**Comment by inghamn** [comment]
Moved the context info below the forms

Fixed in f7af51c132fa23ebf1f046ba3551b60c35041834
