### ISSUE TITLE
Create voting field on seat

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#78]
Most seats are voting seats (the default should be True / Yes), however some seats are designated as non-voting seats. Rather than track this in the seat's name or ID field, it would be more flexible to create a new attribute for seats to track voting capabilities.

**Comment by rbdietz** [comment]
We need to create an internal profile page for staff that describes all of the member requirements and status info (like voting) to facilitate review.

**Comment by charlesbrandt** [comment]
Thanks for the comment, Rick. I have moved that concept to a separate issue (#106). Please add other notes on that topic there. For now, I'd like to keep this issue focused on adding a voting attribute to the seat, which should be easy to add.
