### ISSUE TITLE
Seats and Vacancies report does not fit on screen

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/OnBoard#85]
The seats and vacancies table doesn't fit inside the center content area of the page.

**Comment by charlesbrandt** [comment]
Dan, any ideas on this layout:
https://bloomington.in.gov/onboard/seats

**Comment by hiesterd** [comment]
I have a few ideas I can pitch. I think I can probably present these ideas quickest by working directly with the PHP templates, and deploying them to one of the development instances.

I've been out of the office for a bit. Is the instance at http://rogue.bloomington.in.gov/boards up-to-date? Are there any DB migration scripts that need to be run?

**Comment by hiesterd** [comment]
At least as a first iteration, I can suggest condensing the Seat Code and the Seat Name into one column, like this:

![screen shot 2016-03-08 at 11 44 37 am](https://cloud.githubusercontent.com/assets/10146145/13608551/4a48a096-e523-11e5-955b-af8d92a329ff.png)

Another suggestion I can make is to display the seats for each committee in their own table, and moving the committee name from a table column (the TD value is repetitive, presenting us an option for reduction). That probably requires some changes to logic behind the curtain, and might be more than we need, for now.

Does this give anyone else some ideas?
