### ISSUE TITLE
Separate field for state statute reference for committee info

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#96]
For some boards, there is both a state statute reference and a local statute reference. It would be nice to link to both, if relevant. This would require a separate field to track the state statute url

**Comment by charlesbrandt** [comment]
These fields should be labeled "Municipal Code" and "Statutory Code", respectively

**Comment by rbdietz** [comment]
To be more informative we might want  to go with...
Bloomington Municipal Code and Indiana Statutory Code

On Fri, Mar 11, 2016 at 11:27 AM, Charles Brandt <notifications@github.com>
wrote:

> These fields should be labeled "Municipal Code" and "Statutory Code",
> respectively
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/City-of-Bloomington/OnBoard/issues/96#issuecomment-195439094>
> .
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~
Rick Dietz, Director
Information & Technology Services Dept.
City of Bloomington, Indiana
812.349.3485 (office) 812.340.7958 (cell)
dietzr@bloomington.in.gov

**Comment by charlesbrandt** [comment]
I was thinking that keeping it generic might keep it easier for other municipalities to adopt the system, but if that is easy to configure then more informative is better.

Cliff and I were also discussing keeping associated code references in a separate table to allow an arbitrary number to be assigned to a committee.
