### ISSUE TITLE
Move "Add a Person" button

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#97]
When using the Change Person / Find a Person selection pop up screen, the "Add a Person" button is in a confusing location. 

After filling out the name to search for, a user's natural inclination is to click on the "Add a Person" button given its appearance, rather than the search button, which is the correct action in this case. 

Additionally, it is unclear to users that clicking on the persons name in the search results is what will do the selection action and return that person to the original form. Maybe we should include a button that says "Choose this person"? (could just be the same link)

<img width="900" alt="screen shot 2016-02-11 at 10 00 51 am" src="https://cloud.githubusercontent.com/assets/2225624/12980878/52ccdb82-d0ac-11e5-8b88-5944c3ed89c8.png">

**Comment by inghamn** [comment]
Don't show results unless there's a search

abf1bd2f3627f6fcb8ad920ccd1cb552494bf081
