### ISSUE TITLE
Better error message for no start date

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/OnBoard#98]
When trying to assign a new person to a seat, after selecting the person and selecting a term, no start date was specified. The error message read "Overlapping Terms" but didn't indicate that the start date was a required field (and the real source of the error).

**Comment by charlesbrandt** [comment]
Make membership start date required during appoint

**Comment by inghamn** [comment]
Start date is now a required field

0223ce876961d7a9105211a0d025ead2856ee579
